### ISSUE TITLE
day tables in px issue

### ISSUE THREAD

**Issue by nordbit** [llazzaro/django-scheduler#128]
I'm about this comment it schedule tag:
```
    """
      Display a nice table with occurrences and action buttons.
      Arguments:
      width - width of the table (px)
      width_slot - width of the slot column (px)
      height - height of the table
      start - hour at which the day starts
      end - hour at which the day ends
      increment - size of a time slot (in minutes)
    """
```
I vote against " width", "width_slot", "height " and after that positioning table with css relation "relative-absolute".
It giving me totally mess in my project with incorprated templates. Almost all frontend frameworks and web project are responsive. Better define tables with percent values in css.

I'm against jquery-ui as well, it is a big holy cow, if it is only used for displaying helper widget for date, better leave bare html, any user can implemented this for own needs (twitter-bootstrap plugins for ex.).

**Comment by llazzaro** [comment]
Hi,

I made an initial refactor, removing all template tag parameters except the period.
Old code was doing some crazy algorithms to show the events proportionally to the size visually.

New code will show the event if it happens inside the time slot.

I like much more the old idea, but I want to keep thimgs simple by now. Old code was difficult to understand.

I am not closing this issue since the work is not complete.
Please use pipy version for stable, master branch is unstable branch.
