### ISSUE TITLE
Use SCHEDULER_BASE_CLASSES

### ISSUE THREAD

**Issue by igor-kramer** [llazzaro/django-scheduler#183]
In manage.py shell i write this
`>>from django.utils.module_loading import import_string`
`>>from django.conf import settings`
`>>baseStrings = getattr(settings, 'SCHEDULER_BASE_CLASSES', None)`
`>>[import_string(x) for x in baseStrings]`
`[<class 'studio.models.AbstractModel'>]`

But when i try to import Occurence from my models.py
`from schedule.models import Occurrence`
i catch this ImportError:
`ImportError: Module "studio.models" does not define a "AbstractModel" attribute/class`

**Comment by llazzaro** [comment]
please check the order of your INSTALLED_APPS in the project settings.py. you probably need to have first 'studio' and then 'scheduler'

**Comment by Lucianovici** [comment]
I'm also getting this `ImportError`, although I put my application before the `schedule`.

BTW: Is there a clean way to extend only one model. I need to extend the Event model only, adding two foreign key fields to it.

Thanks! Keep up the good work.

**Comment by Lucianovici** [comment]
Well, it seems like the `ImportError` was normal, because the module I was importing, contained some models inheriting from the `schedule.models` - so I remove all my models and worked as expected.

Moreover, if anybody is interested to just extend specific classes, here is a PR:
https://github.com/llazzaro/django-scheduler/pull/280

**Comment by llazzaro** [comment]
this PR has been merged on commits:
77ead26
35f0b8c
7861232
387fd66
