### ISSUE TITLE
Installed. And now?

### ISSUE THREAD

**Issue by aluiss** [llazzaro/django-scheduler#515]
I have a project in progress, and i likely to add the calendar in it. How do i make it?
The calendar will be part of a web system, but it will not will have a page separate.

**Comment by llazzaro** [comment]
Hi!
Please check https://github.com/llazzaro/django-scheduler-sample
Most of the users of this app use the model or the API.

I don't recommend using the current templates, since those are very old and likely to be deprecated.

I hope to update the documentation with a quickstart, this is a common question.

Thanks!
